[package]
name = "java"
version = "0.1.0"
edition = "2021"

[dependencies.jvm]
path = "../jvm"

[dependencies.clap]
version = "4.3.0"
features = ["derive"]

[[bin]]
name = "java"
path = "src/java.rs"
